legal_advice_builder/urls.py
from django.urls import path

from .admin_views import DocumentCreateView
from .admin_views import DocumentFormView
from .admin_views import DocumentPreviewView
from .admin_views import LawCaseDelete
from .admin_views import LawCaseEdit
from .admin_views import LawCaseList
from .admin_views import LawCasePreview
from .admin_views import QuestionaireCreate
from .admin_views import QuestionaireDeleteView
from .admin_views import QuestionaireDetail
from .admin_views import QuestionDelete
from .admin_views import QuestionUpdate
from .admin_views import AnswerEditView
from .admin_views import DownloadAnswerAsPDFView
from .admin_views import DownloadAnswerAsWordView
from .admin_views import DownloadAnswerAsHTMLView

app_name = 'legal_advice_builder'
urlpatterns = [
    path('', LawCaseList.as_view(), name='law-case-list'),
    path('<int:pk>/edit/', LawCaseEdit.as_view(), name='law-case-edit'),
    path('<int:pk>/delete/', LawCaseDelete.as_view(), name='law-case-delete'),
    path('<int:pk>/preview/', LawCasePreview.as_view(), name='law-case-preview'),
    path('<int:pk>/document/create/', DocumentCreateView.as_view(), name='document-create'),
    path('<int:pk>/questionaire/create/', QuestionaireCreate.as_view(), name='questionaire-create'),
    path('questionaire/<int:pk>/', QuestionaireDetail.as_view(), name='questionaire-detail'),
    path('questionaire/<int:pk>/delete', QuestionaireDeleteView.as_view(), name='questionaire-delete'),
    path('question/<int:pk>/edit', QuestionUpdate.as_view(), name='question-update'),
    path('question/<int:pk>/delete', QuestionDelete.as_view(), name='question-delete'),
    path('document/<int:pk>/edit/', DocumentFormView.as_view(), name='document-update'),
    path('document/<int:pk>/preview/', DocumentPreviewView.as_view(), name='document-detail'),
    path('answer/<int:pk>/edit/', AnswerEditView.as_view(), name='answer-update'),
    path('answer/<int:pk>/pdfdownload/', DownloadAnswerAsPDFView.as_view(), name='answer-pdf-download'),
    path('answer/<int:pk>/worddownload/', DownloadAnswerAsWordView.as_view(), name='answer-word-download'),
    path('answer/<int:pk>/htmldownload/', DownloadAnswerAsHTMLView.as_view(), name='answer-html-download')
]

legal_advice_builder/models.py
from django.conf import settings
from django.db import models
from django.template import Context, Template
from django.utils.translation import gettext_lazy as _
from treebeard.mp_tree import MP_Node

from .utils import generate_answers_dict_for_template


class LawCase(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    result_template = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_first_questionaire(self):
        return self.questionaire_set.first()

    def get_rendered_template(self, answers):
        template = Template(self.result_template)
        result = template.render(Context(
            {'answers': generate_answers_dict_for_template(answers)}
        ))
        return result


class Questionaire(models.Model):
    law_case = models.ForeignKey(LawCase,
                                 on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    short_title = models.CharField(max_length=50, blank=True)
    success_message = models.TextField()
    failure_message = models.TextField()
    unsure_message = models.TextField()
    order = models.IntegerField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order']

    def get_first_question(self):
        return self.questions.first()

    def next(self):
        return Questionaire.objects.filter(
            law_case=self.law_case, order__gt=self.order).first()

    @property
    def questions(self):
        return self.question_set.all().order_by('path')


class Question(MP_Node):

    TEXT = 'TX'
    SINGLE_LINE = 'SL'
    SINGLE_OPTION = 'SO'
    FILE_UPLOAD = 'FU'

    FIELD_TYPES = [
        (TEXT, _('Long multiline Text input')),
        (SINGLE_OPTION, _('Pick one of multiple options')),
        (SINGLE_LINE, _('Short single line text input')),
        (FILE_UPLOAD, _('File Upload'))
    ]

    questionaire = models.ForeignKey(Questionaire,
                                     null=True,
                                     on_delete=models.CASCADE)
    short_title = models.CharField(max_length=50, blank=True)
    text = models.CharField(max_length=200)
    options = models.JSONField(default=dict, blank=True, null=True)
    field_type = models.CharField(
        max_length=2,
        choices=FIELD_TYPES,
        default=SINGLE_OPTION,
    )
    help_text = models.CharField(max_length=200, blank=True)
    parent_option = models.CharField(max_length=200, blank=True)
    failure_options = models.JSONField(default=list, null=True, blank=True)
    success_options = models.JSONField(default=list, null=True, blank=True)
    unsure_options = models.JSONField(default=list, null=True, blank=True)
    information = models.TextField(blank=True)
    success_message = models.TextField(blank=True)
    failure_message = models.TextField(blank=True)
    unsure_message = models.TextField(blank=True)

    def next(self, option=None, text=None):
        if option:
            try:
                return self.get_children().get(parent_option=option)
            except Question.DoesNotExist:
                if option in self.success_options:
                    if self.questionaire.next():
                        return self.questionaire.next().get_first_question()
                    else:
                        return None
        return self.get_children().first()

    def get_status(self, option=None, text=None):
        if option:
            if option in self.success_options:
                return {
                    'success': True,
                    'message': self.get_success_message(),
                    'next': self.next(option, text)
                }
            elif option in self.failure_options:
                return {
                    'failure': True,
                    'message': self.get_failure_message(),
                }
            elif option in self.unsure_options:
                return {
                    'unsure': True,
                    'message': self.get_unsure_message(),
                }
        return {
            'ongoing': True,
            'next': self.next(option, text)
        }

    def get_success_message(self):
        if self.success_message:
            return self.success_message
        return self.questionaire.success_message

    def get_failure_message(self):
        if self.failure_message:
            return self.failure_message
        return self.questionaire.failure_message

    def get_unsure_message(self):
        if self.unsure_message:
            return self.unsure_message
        return self.questionaire.unsure_message

    def get_options_names(self):
        return ', '.join([key for key, value in self.options.items()])

    def get_dict_key(self, option=None, text=None):
        qn = self.questionaire
        qn_key = qn.short_title if qn.short_title else 'questionaire_{}'.format(qn.id)
        question_key = self.short_title if self.short_title else 'question_{}'.format(self.id)
        value = ''
        if option:
            value = self.options.get(option)
        elif text:
            value = text
        return '{}_{}'.format(qn_key, question_key), value

    def __str__(self):
        short_title = self.short_title if self.short_title else ''
        if self.field_type == self.SINGLE_OPTION:
            return '{}: {} {} ({})'.format(
                self.parent_option,
                short_title,
                self.text,
                self.get_options_names())
        else:
            return '{}: {}'.format(short_title, self.text)


class Answer(models.Model):
    law_case = models.ForeignKey(LawCase, on_delete=models.CASCADE)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                null=True, on_delete=models.SET_NULL)
    answers = models.JSONField(null=True, default=dict, blank=True)
    message = models.TextField(blank=True)
    rendered_document = models.TextField(blank=True)

    def __str__(self):
        return self.law_case.title

    def save_rendered_document(self):
        self.rendered_document = self.template
        self.save()

    @property
    def template(self):
        template = Template(self.law_case.result_template)
        result = template.render(Context(
            {'answers': generate_answers_dict_for_template(self.answers)}
        ))
        return result

legal_advice_builder/views.py
from django.http import HttpResponseNotAllowed
from django.template.loader import render_to_string
from django.views.generic import TemplateView

from .forms import RenderedDocumentForm
from .forms import WizardForm
from .mixins import GenerateEditableDocumentMixin
from .mixins import GenerateHTMLDownloadMixin
from .mixins import GeneratePDFDownloadMixin
from .mixins import GenerateWordDownloadMixin
from .mixins import GenrateFormWizardMixin
from .models import Answer
from .models import Question
from .storage import SessionStorage


class FormWizardView(TemplateView,
                     GenrateFormWizardMixin,
                     GenerateEditableDocumentMixin,
                     GenerateWordDownloadMixin,
                     GeneratePDFDownloadMixin,
                     GenerateHTMLDownloadMixin
                     ):
    template_name = 'legal_advice_builder/form_wizard.html'
    download_template_name = 'legal_advice_builder/pdf_download.html'
    wizard_form_class = WizardForm
    document_form_class = RenderedDocumentForm

    def dispatch(self, request, *args, **kwargs):
        self.storage = SessionStorage(
            self.get_prefix(), request
        )
        self.law_case = self.get_lawcase()
        self.allow_download = self.law_case.allow_download
        self.save_answers_enabled = self.law_case.save_answers
        self.answer = None
        if request.POST.get('answer_id'):
            try:
                self.answer = Answer.objects.get(id=request.POST.get('answer_id'))
            except Answer.DoesNotExist:
                pass
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.storage.reset()
        questionaire = self.law_case.get_first_questionaire()
        question = questionaire.get_first_question()
        return self.render_next(question, [])

    def post(self, *args, **kwargs):
        answers = self.storage.get_data().get('answers')
        question = self.storage.get_current_question()
        download = self.request.POST.get('download')
        next_question = self.request.POST.get('next')
        to_previous_question = self.request.POST.get('previous-question')

        if next_question:
            next_question = Question.objects.get(id=next_question)
            return self.render_next(next_question, answers)

        elif download:
            if self.allow_download:
                if self.answer:
                    self.save_document_form(self.request.POST, self.answer)
                if download == 'pdf':
                    return self.render_pdf_download_response(
                        answers, answer=self.answer)
                if download == 'word':
                    return self.render_word_download_response(
                        answers, answer=self.answer)
                if download == 'html':
                    return self.render_html_download_response(
                        answers, answer=self.answer)
            else:
                return HttpResponseNotAllowed(['POST'])

        elif self.answer:
            return self.render_document_form(
                self.request.POST, self.answer, **kwargs)

        elif to_previous_question:
            return self.render_previous_question(answers, question)

        else:
            return self.validate_form_and_get_next(question=question,
                                                   answers=answers,
                                                   data=self.request.POST)

    def get_lawcase(self):
        raise NotImplementedError

    def get_prefix(self):
        return 'legal_advice_builder_{}'.format(self.get_lawcase().id)

    def get_initial_dict(self):
        return {}

    def render_previous_question(self, answers, question):
        try:
            previous_question = self.storage.get_data().get('answers')[-1]
            next_question = Question.objects.get(id=previous_question.get('question'))
            del answers[-1]
            return self.render_next(next_question, answers, initial_data=previous_question)
        except IndexError:
            return self.render_next(question, answers)

    def get_progress(self):
        question = self.storage.get_current_question()
        questions = question.questionaire.questions
        question_count = questions.count()
        question_ids = questions.values_list('id', flat=True)
        answers = self.storage.get_data().get('answers')
        answers_ids = [int(answer.get('question')) for answer in answers]
        answers_count = len([answer_id
                             for answer_id in answers_ids if answer_id in question_ids])
        answers_count = answers_count + 1
        percentage = 0

        if not answers_count == 0 or not question_count == 0:
            percentage = int(answers_count / question_count * 100)

        return question_count, answers_count, percentage

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qcount, acount, perc = self.get_progress()
        context.update({
            'allow_download': self.allow_download,
            'save_answers_enabled': self.save_answers,
            'law_case': self.get_lawcase(),
            'question': self.storage.get_current_question(),
            'current_step': self.law_case.get_index_of_questionaire(
                self.storage.get_current_question().questionaire),
            'step_count': self.law_case.questionaire_count(),
            'progess': perc,
            'answer_count': acount,
            'question_count': qcount,
            'has_previous_question': self.storage.has_previuos_question()
        })
        return context


class PdfDownloadView(TemplateView, GeneratePDFDownloadMixin):
    template_name = 'legal_advice_builder/download.html'
    download_template_name = 'legal_advice_builder/download.html'

    def get_answer(self):
        raise NotImplementedError

    def get_html_string(self):
        ctx = self.get_context_data()
        ctx.update({
            'answer': self.get_answer().rendered_document
        })
        return render_to_string(self.download_template_name, ctx)

    def get(self, request, *args, **kwargs):
        html_string = self.get_html_string()
        return self.generate_pdf_download(html_string)


class WordDownloadView(TemplateView, GenerateWordDownloadMixin):
    template_name = 'legal_advice_builder/download.html'
    download_template_name = 'legal_advice_builder/download.html'

    def get_answer(self):
        raise NotImplementedError

    def get_html_string(self):
        ctx = self.get_context_data()
        ctx.update({
            'answer': self.get_answer().rendered_document
        })
        return render_to_string(self.download_template_name, ctx)

    def get(self, request, *args, **kwargs):
        html_string = self.get_html_string()
        return self.generate_word_download(html_string)


class HTMLDownloadView(TemplateView, GenerateHTMLDownloadMixin):
    template_name = 'legal_advice_builder/download.html'
    download_template_name = 'legal_advice_builder/download.html'

    def get_answer(self):
        raise NotImplementedError

    def get_html_string(self):
        ctx = self.get_context_data()
        ctx.update({
            'answer': self.get_answer().rendered_document
        })
        return render_to_string(self.download_template_name, ctx)

    def get(self, request, *args, **kwargs):
        html_string = self.get_html_string()
        return self.generate_html_download(html_string)

legal_advice_builder/templates/legal_advice_builder/admin/answer_update.html
{% extends 'legal_advice_builder/admin/law_case_detail.html' %}
{% load static i18n %}


{% block main_content %}
<div class="row mb-3">
  <div class="col-8">
    {% if law_case.extra_help %}
    <div class="alert alert-success mt-5" role="alert">
      {{ law_case.extra_help }}
    </div>
    {% endif %}
    {{ form.media }}
    <form method="post">
      {% csrf_token %}
      {% include 'legal_advice_builder/admin/form.html' with form=form %}
      <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-3 mb-3">
        <div class="dropdown">
          <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            {% translate 'Download' %}
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="{% url 'legal_advice_builder:answer-pdf-download' object.id %}">{% translate 'as pdf file' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'legal_advice_builder:answer-word-download' object.id %}">{% translate 'as word document' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'legal_advice_builder:answer-html-download' object.id %}">{% translate 'as html file' %}</a></li>
          </ul>
        </div>
        <input class="btn btn-primary btn-sm" type="submit" value="Änderungen speichern" />
      </div>
    </form>
  </div>
</div>
{% endblock %}

legal_advice_builder/templates/legal_advice_builder/admin/choices_widget_template.html
<input type="hidden" name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>

<div>
  <choice-field
    id="{{ widget.name }}"
    inputtype="{{ widget.type }}"
    name="{{ widget.name }}"
    :initial="{{ widget.value }}"
  >
  </choice-field>
</div>

legal_advice_builder/templates/legal_advice_builder/admin/law_case_detail.html
{% extends 'legal_advice_builder/admin/base.html' %}
{% load i18n %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'legal_advice_builder:law-case-list' %}">
    <i class="bi bi-card-checklist"></i> {% trans 'All forms' %}
</a>
<div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
    <ul class="navbar-nav me-auto">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="">{{ lawcase.title }}</a>
        </li>
    </ul>
</div>
{% if lawcase.questions_count > 0 %}
<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
    <ul class="navbar-nav ms-auto">
        <li class="nav-item">
            <a class="btn btn-outline-dark" target="_blank" href="{% url 'legal_advice_builder:law-case-preview' lawcase.id %}"><i class="bi bi-eye"></i> {% trans 'preview' %}</a>
        </li>
    </ul>
</div>
{% endif %}

{% endblock %}

{% block content %}
<div class="row">
    <div class="col-3 col-xxl-2 border-end border-light min-vh-100">
        <div class="pt-3">
        {% block navigation %}
        <div class="card">
            <div class="card-header">
                {% trans 'Questionaires' %}
            </div>
            <ul class="list-group list-group-flush">
                {% if lawcase.questionaire_set.count > 1 %}
                {% for qn in lawcase.questionaire_set.all %}
                <a class="list-group-item {% if questionaire == qn %}active{% endif %}"
                    href="{% url 'legal_advice_builder:questionaire-detail' qn.id %}">
                        <i class="bi bi-list-task"></i> {{ qn }}
                    {% if qn.has_error %}
                        <span class="badge bg-danger rounded-pill"><i class="bi bi-exclamation-lg"></i></span>
                    {% endif %}
                </a>
                {% endfor %}
                {% endif %}
            </ul>
            <button class="btn btn-link btn-sm mx-1 my-3" type="button" data-bs-toggle="modal" data-bs-target="#newQuestionaireForm">{% trans 'Add questionaire' %}</button>
        </div>

        <div class="card mt-3 ">
            <div class="card-header">
                {% trans 'Document' %}
            </div>
            {% if lawcase.document %}
            <ul class="list-group list-group-flush">
                <a href="{% url 'legal_advice_builder:document-detail' lawcase.id %}" class="list-group-item"><i class="bi bi-file-earmark-text"></i> {% trans 'Template' %}</a>
            </ul>
            {% else %}
            <button class="btn btn-link btn-sm mx-1 my-3" type="button" data-bs-toggle="modal" data-bs-target="#newDocumentForm">{% trans 'Add document' %}</button>
            {% endif %}
        </div>

        {% endblock %}
        </div>
    </div>

    <div class="col-9 col-xxl-10 mt-3">
        {% block main_content %}{% endblock %}
    </div>
    <div class="col-1 border-start border-light bg-white min-vh-100"></div>
</div>

{% if questionaire %}
<div class="modal fade" id="newDocumentForm" tabindex="-1" aria-labelledby="newDocumentForm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newDocumentFormLabel">{% trans 'Add new document' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'legal_advice_builder:document-create' lawcase.id %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    {% include 'legal_advice_builder/admin/form.html' with form=document_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-sm" data-bs-dismiss="modal">{% trans 'Cancel' %}</button>
                    <button type="submit" name="question_create" class="btn btn-primary btn-sm">{% trans 'Save' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

<div class="modal fade" id="newQuestionaireForm" tabindex="-1" aria-labelledby="newQuestionaireForm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newQuestionaireFormLabel">{% trans 'Add new questionaire' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'legal_advice_builder:questionaire-create' lawcase.id  %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    {% include 'legal_advice_builder/admin/form.html' with form=questionaire_form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-sm" data-bs-dismiss="modal">{% trans 'Close' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm">{% trans 'Save' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

legal_advice_builder/templates/legal_advice_builder/admin/law_case_list.html
{% extends 'legal_advice_builder/admin/base.html' %}
{% load i18n %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'legal_advice_builder:law-case-list' %}">
    <i class="bi bi-card-checklist"></i> {% trans 'All forms' %}
</a>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col mt-3 mb-3">
        <div class="row row-cols-sm-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card h-100 bg-primary">
                    <button class="btn w-100 h-100 text-white text-uppercase fw-bolder fs-5" type="button"
                        data-bs-toggle="modal" data-bs-target="#newLawCaseForm">
                        <i class="bi bi-plus"></i> {% trans 'new form' %}
                    </button>
                </div>
            </div>
            {% for law_case in object_list %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-body">
                            <a href="{% url 'legal_advice_builder:questionaire-detail' law_case.first_questionaire.id %}"
                                class="text-decoration-none text-body">
                                <h5 class="card-title">{{ law_case.title }}</h5>
                                <p class="card-text">{{ law_case.description }}</p>
                            </a>
                        </div>
                        <div class="card-footer bg-white pe-0 py-0">
                            <div class="row justify-content-between me-0">
                                <div class="col d-flex align-items-center">
                                    <small class="text-muted">
                                        {% blocktranslate count counter=law_case.answer_set.count %}
                                        One answer
                                        {% plural %}
                                        {{ counter }} answers
                                        {% endblocktranslate %}
                                    </small>
                                </div>
                                <div class="col pe-0">
                                    <div class="btn-group float-end">
                                        <button type="button" class="btn btn-link border-start"
                                            data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="bi bi-three-dots-vertical"></i>
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-end">
                                            <li><a class="dropdown-item" target="_blank"
                                                    href="{% url 'legal_advice_builder:law-case-preview' law_case.id %}"><i class="bi bi-eye"></i> {% trans 'preview' %}</a>
                                            </li>
                                            <li class="dropdown-item" href="#">
                                                <button type="button"
                                                    class="btn btn-link p-0 text-decoration-none text-body w-100 text-start"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#lawcaseModal{{ law_case.id }}">
                                                    {% trans 'edit' %}
                                                </button>
                                            </li>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li class="dropdown-item" href="#">
                                                <button type="button"
                                                    class="btn btn-link p-0 text-decoration-none text-body w-100 text-start"
                                                    data-bs-toggle="modal"
                                                    data-bs-target="#lawcaseDeleteModal{{ law_case.id }}">
                                                    {% trans 'delete' %}
                                                </button>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% for law_case in object_list %}
<div class="modal fade" id="lawcaseDeleteModal{{ law_case.id }}" tabindex="-1"
    aria-labelledby="lawcaseDeleteModal{{ law_case.id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lawcaseDeleteModal{{ law_case.id }}Label">{% blocktrans with title=law_case.title %} Do you want to delete "{{ title }}"? {% endblocktrans %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-link btn-sm" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
                        <form action="{% url 'legal_advice_builder:law-case-delete' law_case.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-sm" value="DELETE">{% trans 'delete' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% for law_case_form in update_forms %}
<div class="modal fade" id="lawcaseModal{{ law_case_form.0 }}" tabindex="-1"
    aria-labelledby="lawcaseModal{{ law_case_form.0 }}lLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lawcaseModal{{ law_case.id }}Label">{{ law_case.title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'legal_advice_builder:law-case-edit' law_case_form.0 %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    {% include 'legal_advice_builder/admin/form.html' with form=law_case_form.1 %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-sm" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm">{% trans 'Save' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}

<div class="modal fade" id="newLawCaseForm" tabindex="-1" aria-labelledby="newLawCaseForm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newQuestionFormLabel">{% trans 'Add new form' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    {% include 'legal_advice_builder/admin/form.html' with form=form %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-sm" data-bs-dismiss="modal">{% trans 'cancel' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm">{% trans 'Save' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}